[package]
name = "heart_beat"
version = "0.1.0"
authors = ["Arvinder Dhanoa <awsomearvinder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi_wrapper = {path = "../winapi_wrapper"}
